import type { Metadata } from "next";
import ConvexClerkProvider from "@/ConvexClerkProvider";
import { Inter } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";

// Local Geist fonts
const geistSans = localFont({
  src: "../fonts/Geist-Regular.woff2",
  variable: "--font-geist-sans",
  weight: "400",
});

const geistMono = localFont({
  src: "../fonts/GeistMono-Regular.woff2",
  variable: "--font-geist-mono",
  weight: "400",
});
export const metadata: Metadata = {
  title: "Clerk Next.js Quickstart",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
   
      <html lang="en" className={`${geistSans.variable} ${geistMono.variable}`}>
  <body className="antialiased">
 <ConvexClerkProvider>
          <Navbar />

          {/* Background gradient and grid */}
          <div className="fixed inset-0 -z-10">
            <div className="absolute inset-0 bg-gradient-to-b from-background via-background to-background"></div>
            <div className="absolute inset-0 bg-[linear-gradient(var(--cyber-grid-color)_1px,transparent_1px),linear-gradient(90deg,var(--cyber-grid-color)_1px,transparent_1px)] bg-[size:20px_20px]"></div>
          </div>

          <main className="pt-24 flex-grow">
          {children}
        </main>

          <Footer />
          </ConvexClerkProvider>
        </body>
      </html>
    
  );
}
